### ISSUE TITLE
Apollo client 3 support

### ISSUE THREAD

**Issue by paales** [adobe/apollo-link-mutation-queue#5]
Currently the v2 package `apollo-link` is used, should become `@apollo/client`

https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#apollo-link-and-apollo-link-http

Getting the following error:
![Schermafbeelding 2020-07-22 om 12 19 06](https://user-images.githubusercontent.com/1244416/88165172-8ec6e380-cc15-11ea-9783-f8f314b0a34e.png)

**Comment by sirugh** [comment]
Odd - I'm able to use the latest publish with my [Apollo v3 PR](https://github.com/magento/pwa-studio/pull/2560) in PWA Studio without seeing this error. Could you provide a sandbox link with repro if possible?

**Comment by paales** [comment]
I think that is still working because it's not using typescript? But might increase the bundle size as it is including it twice from different repositories?

**Comment by paales** [comment]
Bumping this issue 😄 

Still getting:

```
Type 'MutationQueueLink' is not assignable to type 'ApolloLink | RequestHandler'.
  Type 'MutationQueueLink' is missing the following properties from type 'ApolloLink': onError, setOnErrorts(2322)
```

To work around it, I have to do the following:
```
(new MutationQueueLink() as unknown) as ApolloLink,
```

The solution probably:

The dependency `apollo-link` should be replaced by `@apollo/client` as the typescript definitions aren't the same :)

**Comment by sirugh** [comment]
@paales thanks for the bump. I tried to upgrade to `@apollo/client` but I keep running into problems. Think you could give it a shot? I'm sure you've got more ts knowledge and debugging experience than I do.

**Comment by sirugh** [comment]
After posting that I gave it another shot and I think I fixed it. Would appreciate your review :)

**Comment by markymc** [comment]
Hi all, any news on this?

**Comment by cesarve77** [comment]
You can solve this using resolutions in yarn 

package.json
```
  "resolutions": {
    "@apollo/client": "3.6.6",
  }
```
more info here: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by sirugh** [comment]
Oh, I believe this has been resolved, I just forgot to close the issue.

**Comment by cesarve77** [comment]
is not solved.
but I think it ca be solved changing dependencies
from
```
 "@apollo/client": "^3.0.0"
```
to a peer dependencies:
```
 "@apollo/client": ">=3.0.0"
```

**Comment by paales** [comment]
@cesarve77 I think that does the trick :) Maybe move the other dependency as well.

**Comment by sirugh** [comment]
Could you clarify how this issue is not solved? We have upgraded apollo v3 as of #8 and performed a release. Are you still getting an error? Perhaps you can open a new issue/PR for anything you are seeing.
